prod/objects/Simap_Adjudications_et_mises_a_jour__c/Simap_Adjudications_et_mises_a_jour__c.object-meta.xml
<CustomObject>
    <label>Simap Adjudications et mises a jour</label>
    <nameField>
        <label>Awards and updates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simap Adjudications et mises a jour</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/objects/Simap_Cantons__c/Simap_Cantons__c.object-meta.xml
<CustomObject>
    <label>Simap Canton</label>
    <nameField>
        <label>Simap Cantons Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simap Cantons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod/objects/Simap_Cantons__c/fields/abbreviation__c.field-meta.xml
<CustomField>
    <fullName>abbreviation__c</fullName>
    <label>abbreviation</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

test/objects/Simap_Code_CPV__c/Simap_Code_CPV__c.object-meta.xml
<CustomObject>
    <label>Simap Code CPV</label>
    <nameField>
        <label>Simap Code CPV Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simap Codes CPV</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/objects/Simap_Federal_Entities__c/Simap_Federal_Entities__c.object-meta.xml
<CustomObject>
    <label>Simap Federal Entity</label>
    <nameField>
        <label>Simap Federal Entities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simap Federal Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod/objects/Simap_Type_de_procedure__c/Simap_Type_de_procedure__c.object-meta.xml
<CustomObject>
    <label>Simap Type de procedure</label>
    <nameField>
        <label>Type de procedure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simap Types de procedure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prod/objects/Simap_Type_de_Publication__c/Simap_Type_de_Publication__c.object-meta.xml
<CustomObject>
    <label>Simap Type de Publication</label>
    <nameField>
        <label>Type de Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simap Types de publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/classes/SimapUtils.cls
public with sharing class SimapUtils {

    public class SimapUtilsException extends Exception {}

    public static final Integer CUSTOM_FIELD_MAX_LENGTH = 225;
    public static final String ADDRESS_SEPARATOR = ', ';

    public static List<SObject> getSelectedCantonalEntities() {
        return [
            SELECT 
                Id,
                Name,
                simap_id__c,
                Abbreviation__c,
                inclus_dans_API_SIMAP__c
            FROM
                Simap_Cantons__c
            WHERE
                inclus_dans_API_SIMAP__c = true
            WITH USER_MODE
        ];
    }

    public static List<SObject> getSelectedFederalEntities() {
        return [
            SELECT
                Id,
                Name,
                simap_id__c,
                inclus_dans_API_SIMAP__c
            FROM 
                Simap_Federal_Entities__c
            WHERE
                inclus_dans_API_SIMAP__c = true
            WITH USER_MODE
        ];
    }

    public static List<SObject> getSelectedPublicationTypes() {
        return [
            SELECT
                Id,
                Name,
                simap_value__c,
                inclus_dans_API_SIMAP__c
            FROM 
                Simap_Type_de_Publication__c
            WHERE
                inclus_dans_API_SIMAP__c = true
            WITH USER_MODE
        ];
    }

    public static List<SObject> getSelectedProcedureTypes() {
        return [
            SELECT
                Id,
                Name,
                simap_value__c,
                inclus_dans_API_SIMAP__c
            FROM 
                Simap_Type_de_procedure__c
            WHERE
                inclus_dans_API_SIMAP__c = true
            WITH USER_MODE
        ];
    }

    public static List<SObject> getSelectedAdjudications() {
        return [
            SELECT
                Id,
                Name,
                simap_value__c,
                inclus_dans_API_SIMAP__c
            FROM 
                Simap_Adjudications_et_mises_a_jour__c
            WHERE
                inclus_dans_API_SIMAP__c = true
            WITH USER_MODE
        ];
    }

    public static List<Simap_Code_CPV__c> getSelectedSimapCodesCPV() {
        return [
            SELECT
                Id,
                Name,
                Code_CPV__c,
                appliquer_recherche_CANTONALE__c,
                appliquer_recherche_FEDERALE__c
            FROM
                Simap_Code_CPV__c
            WHERE
                appliquer_recherche_CANTONALE__c = true
            OR
                appliquer_recherche_FEDERALE__c = true
            WITH USER_MODE
        ];
    }

    public static String checkAndTrimLength(String fieldValue) {
        if (fieldValue == null) {
            return null;
        }
        fieldValue = fieldValue.trim();
        return fieldValue.length() > CUSTOM_FIELD_MAX_LENGTH ? fieldValue.substring(0, CUSTOM_FIELD_MAX_LENGTH) : fieldValue;
    }

    public static String getValidField(SimapHeadersService.SimapSwissLangSet fieldMap) {
        if (fieldMap == null) {
            return '';
        }
        if (fieldMap.fr != null && fieldMap.fr != '') {
            return fieldMap.fr;
        } else if (fieldMap.de != null && fieldMap.de != '') {
            return fieldMap.de;
        } else if (fieldMap.it != null && fieldMap.it != '') {
            return fieldMap.it;
        } else if (fieldMap.en != null && fieldMap.en != '') {
            return fieldMap.en;
        } else {
            return null;
        }
    }

    public static String addressConverter(SimapPublicationDetailService.SimapAdress addr) {
        if (
            addr?.city == null ||
            addr?.postalCode == null ||
            addr?.street == null
        ) {
            return null;
        }
        String parsedAddress = '';

        String parsedStreet = getValidField(addr.street);
        String parsedCity = getValidField(addr.city);

        List<String> addressParts = new List<String> {
            parsedStreet,
            parsedCity,
            addr.cantonId,
            addr.countryId,
            addr.postalCode
        };

        for(String addressPart : addressParts) {
            if(!String.isBlank(addressPart) && addressPart != null) {
                parsedAddress += addressPart + ADDRESS_SEPARATOR;
            }
        }

        parsedAddress = parsedAddress.removeEnd(ADDRESS_SEPARATOR);
        return parsedAddress;
    }

    public static String getValidPublicationTitle(SimapHeadersService.PublicationDeserializer publication) {
        return checkAndTrimLength(getValidField(publication.title));
    }

    public static String getValidPublicationProcOfficeName(SimapHeadersService.PublicationDeserializer publication) {
        return checkAndTrimLength(getValidField(publication.procOfficeName));
    }

    public static String getValidCantonValue(SimapPublicationDetailService.ProjectInfo projectInfo) {
        if (projectInfo.procOfficeAddress?.cantonId != null) {
            String cantonName = getCantonNameByAbbreviation(projectInfo.procOfficeAddress.cantonId);
            if (cantonName != null) {
                return cantonName;
            }
        }
        if (projectInfo.procurementRecipientAddress?.cantonId != null) {
            String cantonName = getCantonNameByAbbreviation(projectInfo.procurementRecipientAddress.cantonId);
            if (cantonName != null) {
                return cantonName;
            }
        }
        if (projectInfo.offerAddress?.cantonId != null) {
            String cantonName = getCantonNameByAbbreviation(projectInfo.offerAddress.cantonId);
            if (cantonName != null) {
                return cantonName;
            }
        }

        return null;
    }

    public static String getCantonNameByAbbreviation(String cantonId) {
        List<SObject> simapCantonalEntities = SimapUtils.getSelectedCantonalEntities();
        for (SObject entity : simapCantonalEntities) {
            if ((String) entity.get('Abbreviation__c') == cantonId) {
                return (String) entity.get('Name');
            }
        }
        return null;
    }

}