prod/objects/Opportunity/fields/latitude__c.field-meta.xml
<CustomField>
    <fullName>latitude__c</fullName>
    <label>latitude</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

prod/objects/Opportunity/fields/longitude__c.field-meta.xml
<CustomField>
    <fullName>longitude__c</fullName>
    <label>longitude</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

prod/classes/OpportunityQueueableTest.cls
@IsTest
public class OpportunityQueueableTest {

    @TestSetup
    static void setupTestData() {
        OpportunityServiceTest.setUpTestEnv();
    }

    @IsTest
    static void testOpportunityQueueable() {
        Test.setMock(HttpCalloutMock.class, new MockHttpOpenStreetMapResponse());

        Opportunity testOpportunity = [SELECT Id FROM Opportunity LIMIT 1];

        Test.startTest();
        System.enqueueJob(new OpportunityQueueable(testOpportunity.Id));
        Test.stopTest();

        Opportunity updatedOpp = [SELECT latitude__c, longitude__c FROM Opportunity WHERE Id = :testOpportunity.Id];

        System.assertNotEquals(null, updatedOpp.latitude__c, 'Latitude should be set');
        System.assertNotEquals(null, updatedOpp.longitude__c, 'Longitude should be set');
    }
}